CREATE TABLE `asha-349306.History_usecase1_dev.History_uc1_table_dev`
(
  SNAPSHOTDATE	DATE NOT NULL
,EMPLID 	STRING NULL
,EMPL_CLASS	STRING
,POSITION_NBR	INTEGER
,POSITION_DESCRIPTION	STRING
,DEPTID	STRING
,DIRECOTRATE_DESCRIPTION	STRING
,DEPARTMENT_DESCRIPTION	STRING
,ACCT_CD	STRING
,LOCATION	STRING
,ORG_LEVEL	INT64
,L1_EMPLID	STRING
,L1_NAME	STRING
,L1_POSITION_NBR	STRING
,L1_POSITION_NAME	STRING
,L2_EMPLID	STRING
,L2_NAME	STRING
,L2_POSITION_NBR	STRING
,L2_POSITION_NAME	
,L3_EMPLID	STRING
,L3_NAME	STRING
,L3_POSITION_NBR	STRING
,L3_POSITION_NAME	STRING
,LEVEL	INT64
,HIRE_DATE	DATE
,REHIRE_DT	DATE
,SERVICE_DT	DATE
,REAL_SERVICE_DATE	DATE
,LAST_UPDATED	TIMESTAMP
);